name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github'
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '15 6 * * SUN'
  workflow_dispatch: 
    inputs:
      environment:
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Event name
        run: echo "This is the name of the trigger event ${{ github.event_name }}"
      - name: Branch name
        run: echo "And here we have the branch name${{ github.ref }}"
        
      - uses: actions/checkout@v3.3.0
      - name: List files in repository
        run: |
          echo "And finally ${{ github.repository }} contains the following files:"
          tree
  Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    environment: Test
    steps:
      - run: echo "Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    environment: Load-Test
    steps:
      - run: |
          echo "Testing..."
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    if: github.event_name == 'workflow_dispatch'
    environment: 
      name: Production
      url: https://writeabout.net
    steps:
      - run: |
         echo "Step 1..."
         sleep 10
      - run: |
         echo "Step 2..."
         sleep 10
      - run: |
         echo "Step 3..."
         sleep 10
      - run: |
         echo "Step 4..."
         sleep 10
      - run: |
         echo "Step 5..."
         sleep 10
      
      
